import Link from 'next/link';
import { appConfig } from '../../config';

export const metadata = {
  title: `Terms of Service | ${appConfig.name}`,
  description: `Read our Terms of Service. Understand the rules, responsibilities, and constraints when using ${appConfig.name} AI-powered background removal platform.`,
};

export default function Terms() {
  return (
    <div className="app-container glass-panel content-card">
      <Link href="/" className="back-link">
        <i className="fa-solid fa-arrow-left"></i> Back to Tool
      </Link>
      
      <h1>Terms of Service</h1>
      <span className="last-updated">Last Updated: February 22, 2026</span>
      
      <p>Welcome to {appConfig.name}. These terms and conditions outline the rules and regulations for the use of {appConfig.name}'s Website.</p>
      <p>By accessing this website we assume you accept these terms and conditions. Do not continue to use {appConfig.name} if you do not agree to take all of the terms and conditions stated on this page.</p>

      <h2>1. User Rights & Responsibilities</h2>
      <p>{appConfig.name} provides a free service enabling users to digitally remove backgrounds from uploaded images using an AI model. You agree that:</p>
      <ul>
        <li>You hold the legal copyright or have obtained proper explicit authorization for all images you upload to our service.</li>
        <li>You will not upload images that are illegal, offensive, explicit, or designed to commit fraud.</li>
        <li>You will not attempt to reverse engineer, scrape, spam, or launch denial-of-service attacks against our infrastructure.</li>
      </ul>
      
      <h2>2. License to Use Output</h2>
      <p>You retain full ownership of the original images you upload to {appConfig.name}. We do not claim any copyright over your files. Moreover, {appConfig.name} does not claim ownership over the processed transparent image (the output) generated by our AI. You are free to use these generated results for both personal and commercial purposes without paying royalties to {appConfig.name}.</p>

      <h2>3. Service Availability and "As Is" Limitation</h2>
      <p>{appConfig.name} provides its services strictly on an "as is" and "as available" basis.</p>
      <ul>
        <li>We make no representations or warranties of any kind regarding the accuracy, reliability, or quality of the AI background removal output.</li>
        <li>{appConfig.name} does not guarantee that the site or its services will be available uninterrupted, secure, or free from errors. We reserve the right to restrict access to parts of or the entirety of our service at any moment without notice.</li>
      </ul>
      
      <h2>5. Disclaimer of Liability</h2>
      <p>In no event shall {appConfig.name}, nor any of its developers, officers, or partners, be held liable for anything arising out of or in any way connected with your use of this Website. Under no circumstance shall {appConfig.name} be held liable for any indirect, consequential, or special damages, resulting from the loss of data, loss of copyright revenue, or server downtimes connected with your use of this Website.</p>

      <h2>6. Governing Law</h2>
      <p>These Terms will be governed by and interpreted in accordance with standard internet jurisdictions, and you submit to the non-exclusive jurisdiction of the state and federal courts for the resolution of any disputes.</p>
    </div>
  );
}
